//API call 1.1
GET http://localhost:3000/todos/?status=TO%20DO
###

//API call 1.2
GET http://localhost:3000/todos/?priority=HIGH
###

//API call 1.3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

//API call 1.4
GET http://localhost:3000/todos/?search_q=HTML
###

//API call 2
GET http://localhost:3000/todos/2/
###


//API call 3
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Python",
  "priority": "HIGH",
  "status": "IN PROGRESS"
}

###
//API call 4.1
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "status": "DONE" }

###
//API call 4.2
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "priority": "HIGH" }

###
//API call 4.3
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "todo": "Some task" }

###
//API call 5
DELETE http://localhost:3000/todos/4/